author: SDSC
description: Cyberinfrastructure-enabled Machine Learning Project
keyword: SDSC, HPC, CIML

excerpt_link: Read more

menu:
    Home: /
    About: /about/
    Training Events: /events/
    Training Material: /training/
    CIML Blog: /blog/
    Contact: /contact/

# highlight
highlight: tomorrow

# catalog
catalog: false

# donate
donate: false

# qrcode
qrcode: false

# comment
# you can set utterances, gitment, uyan or disqus
comment:

# utterances config
utterances_repo: # e.g. GitHubAccount/RepoForUtterances
utterances_issue_term: pathname # you can see other available options at 'https://utteranc.es/'
utterances_theme: github-light # you can see other available options at 'https://utteranc.es/'

google_analytics:
# disqus config
disqus_shortname:

about:
    banner: ""
    avatar: https://avatars.githubusercontent.com/u/46249297?s=200&v=4
    description: "San Diego Supercomputer Center"
    github_username: sdsc-hpc-students

# MathJax Support
mathjax:
    enable: true
    per_page: false
    cdn: //cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-AMS-MML_HTMLorMML

# Local Search Support
local_search:
    enable: true
